M48
; DRILL file {KiCad 9.0.1} date 2025-05-21T12:09:34+0100
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2025-05-21T12:09:34+01:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,9.0.1
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0256
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.0335
%
G90
G05
T1
X3.9854Y-4.7474
X4.213Y-4.7474
T2
X5.45Y-4.6528
X5.45Y-4.889
X6.0Y-4.6528
X6.0Y-4.889
M30
